# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool: pool1

steps:
- script: |
    echo Download AZ Deployment tools
    git clone https://github.com/anderp2/az.tools.git
    ls -l
    echo PWD: `pwd`
    echo ENV: `env`
  displayName: 'Get Deployment tools'
- task: Bash@3
  inputs:
    filePath: 'az.tools/terraform_deploy.sh'
  env:
    ARM_SUBSCRIPTION_ID: $(TF_ARM_SUBSCRIPTION_ID)
    ARM_CLIENT_ID:       $(TF_ARM_CLIENT_ID)
    ARM_CLIENT_SECRET:   $(TF_ARM_CLIENT_SECRET)
    ARM_TENANT_ID:       $(TF_ARM_TENANT_ID) 
  


