# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool: pool1

trigger: none

steps:
- script: |
    echo Download AZ Deployment tools
    git clone https://github.com/anderp2/az.tools.git
    ls -l
    echo PWD: `pwd`
    echo ENV: `env`
  displayName: 'Get Deployment tools'
- task: AzureKeyVault@2
  inputs:
    azureSubscription: 'Azure subscription 1(24249cfa-81f0-427c-932d-621edd58f968)'
    KeyVaultName: 'kv-security-ci'
    SecretsFilter: '*'
    RunAsPreJob: true
    
- task: Bash@3
  inputs:
    filePath: 'az.tools/terraform_deploy.sh'
  env:
    ARM_SUBSCRIPTION_ID: $(kv-arm-subscription-id)
    ARM_CLIENT_ID:       $(kv-arm-client-id)
    ARM_CLIENT_SECRET:   $(kv-arm-client-secret)
    ARM_TENANT_ID:       $(kv-arm-tenant-id)
    ARM_ACCESS_KEY:      $(kv-arm-access-key)
    TF_VAR_resource_group: $(resource-group)
    TF_VAR_vnet1: $(vnet1)
    TF_VAR_subnet1: $(subnet1)
    TF_VAR_vm1_name: $(vm1-name)
    TF_VAR_vm1_size: $(vm1-size)
    TF_VAR_vm1_publisher: $(vm1-publisher)
    TF_VAR_vm1_sku: $(vm1-sku)
    TF_VAR_vm1_offer: $(vm1-offer)
    TF_VAR_vm1_version: $(vm1-version)
    
    
  


